"""first revision

Revision ID: 91c277ebd84f
Revises: f77db28332bd
Create Date: 2024-04-13 10:18:34.645635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c277ebd84f'
down_revision: Union[str, None] = 'f77db28332bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'notifications', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='unique')
    # ### end Alembic commands ###
