"""first revision

Revision ID: 7aab7a3de6fc
Revises: cfe87a167899
Create Date: 2024-03-21 16:25:19.023872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aab7a3de6fc'
down_revision: Union[str, None] = 'cfe87a167899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messagereactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'message_id')
    )
    op.create_unique_constraint(None, 'chatrooms', ['id'])
    op.create_unique_constraint(None, 'messages', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'chatrooms', type_='unique')
    op.drop_table('messagereactions')
    # ### end Alembic commands ###
