# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terragrunt-aws-sre"
    dynamodb_table = "terraform-lock-table"
    key            = "./terraform.tfstate"
    profile        = "dylan"
    region         = "us-east-1"
    role_arn       = "arn:aws:iam::984119170260:role/terraform-role"
  }
}
