version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - /tmp/postgre:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - testing-network


  connection:
    build: .
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST : ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - postgres
    networks:
      - testing-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - testing-network   


networks:
  testing-network:
    external: true